title: Fish n Fly
description: Traveling farther. Fishing better. Stories around the world.
theme: minima

header_pages:
  - about.md
  - travel.md
  - stories.md
  - contact.md

footer:
  show_powered_by: false

# Make all "pages" use the styled Minima page layout by default
defaults:
  - scope:
      path: ""         # applies to the whole site
      type: "pages"    # only to pages (not posts)
    values:
      layout: page

