title: Fish n Fly
description: Traveling farther. Fishing better. Stories around the world.
theme: minima
url: "https://fishnfly.net"

image: /assets/images/social/fishnfly-og.jpg

header_pages:
  - about.md
  - travel.md
  - stories.md
  - contact.md

footer:
  show_powered_by: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

